require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '13.0'

target 'Vayy Up' do
  pod 'react-native-ffmpeg/https-gpl-lts', :podspec => '../node_modules/react-native-ffmpeg/react-native-ffmpeg.podspec'
  
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  
  
end

